### ISSUE TITLE
Demo to investor (Wednesday 3-11)

### ISSUE THREAD

**Issue by thala321** [massbitprotocol/massbitroute#10]
**Tasks**
- [x] User runs a community node in GCP
  - [x] Ethereum (ganache)
  - [x] Solana
- [x] Script / Terraform auto-install software and call APIs to DNS server (send CPU, rams info,...)
  - [x] user registers as a node 
  - [x] user registers as a gateway 
  - [x] `new` Record video demo (4h 3-11)

**Demo scenarios**
- Open two existing nodes in Asia, Europe
- Run a script to install the massbit agent, automatically ask for the key from our system, use the key to register to the provider at the nearest location (Asia or Europe). 
- In the portal (or Grafana), see the node has traffic & stats. 
- Also, show DNS config

**Note**
- No staking work
