### ISSUE TITLE
Partners Manager

### ISSUE THREAD

**Issue by hughiephan** [massbitprotocol/massbitroute#20]
ETA: 10/12
Node Manager
 - [x] `new` refactor gateway, gateway manager, register
 - [x] `new` websocket api communicate status node/gw and node/gw managers #49 
 - [x] Wireframe & setup base API
 - [x] Register & get script install #50  
 - [x] View stat/healthy of your nodes  (in-progress) 24-11 -> 25-11 -> 26-11
 - [x] Create token for API control 
 - [x] Control node via GUI & CLI 
 - [x] Rules 
   - Set multiple vars
   - Allow Limit rate
   - Allow Whitelist IP
   - Allow Method Call
   - Allow Origin
   - Allow Useragent
 - [x] Refactor rules

Gateway Manager
 - [x] Wireframe & setup base API
 - [x] Register & get script install #50 
 - [x]  `new` websocket api communicate status node/gw and node/gw managers #49 
 - [x] View stat/healthy your gateway  (in-progress) 24-11 -> 25-11 -> 26-11
 - [x] Create token for API control  
 - [x] Control GW via GUI & CLI
 - [x] Rules 
   - Set multiple vars
   - Allow Limit rate
   - Allow Whitelist IP
   - Allow Method Call
   - Allow Origin
   - Allow Useragent
- [x] Refactor rules
